/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PREVNEXT_H_RPCGEN
#define _PREVNEXT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PREVNEXT 2000001
#define PREVNEXT_VERSAO1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PREV 1
extern  int * prev_1(int *, CLIENT *);
extern  int * prev_1_svc(int *, struct svc_req *);
#define NEXT 2
extern  int * next_1(int *, CLIENT *);
extern  int * next_1_svc(int *, struct svc_req *);
extern int prevnext_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PREV 1
extern  int * prev_1();
extern  int * prev_1_svc();
#define NEXT 2
extern  int * next_1();
extern  int * next_1_svc();
extern int prevnext_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PREVNEXT_H_RPCGEN */
