/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prevnext.h"


void
prevnext_1(char *host, int num)
{
	CLIENT *clnt;
	int  *result_1;
	int  prev_1_arg;
	int  *result_2;
	int  next_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PREVNEXT, PREVNEXT_VERSAO1, "tcp");
	// clnt = clnt_create (host, PREVNEXT, PREVNEXT_VERSAO1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//result_1 = prev_1(&prev_1_arg, clnt);
	result_1 = prev_1(&num, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	//result_2 = next_1(&next_1_arg, clnt);
	result_2 = next_1(&num, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Prev: %d\n", *result_1);
	printf("Next: %d\n", *result_2);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int num;

	if (argc < 3) {
		printf ("usage: %s server_host num\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	num = atoi(argv[2]);
	prevnext_1 (host, num);
exit (0);
}
